FROM nginx:stable-alpine

RUN apk update \
    && apk add vim \
    && apk add cmatrix

WORKDIR /usr/share/nginx/html/images

RUN curl -o tool.gif https://media.tenor.com/qU7kKSP7JgsAAAAC/big-brain-lateralus.gif